version: '3.8'
services:
  minesweeper_java:
    image: minesweeper:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8084:8084"


  minesweeper_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: minesweeper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2705
    ports:
      - "5432:5432"
    volumes:
      - ~/db_data:/var/lib/postgresql/data
